/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AuthAuthRouteImport } from './routes/_auth/auth'
import { Route as AdminWidgetRouteImport } from './routes/_admin/widget'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminEditorRouteImport } from './routes/_admin/editor'
import { Route as AdminRequestsIndexRouteImport } from './routes/_admin/requests/index'
import { Route as AdminBoardsIndexRouteImport } from './routes/_admin/boards/index'
import { Route as AuthAcceptInvitationIdRouteImport } from './routes/_auth/accept-invitation.$id'
import { Route as AdminSettingsPricingRouteImport } from './routes/_admin/settings/pricing'
import { Route as AdminSettingsMembersRouteImport } from './routes/_admin/settings/members'
import { Route as AdminSettingsGeneralRouteImport } from './routes/_admin/settings/general'
import { Route as AdminSettingsFeedbackRouteImport } from './routes/_admin/settings/feedback'
import { Route as AdminSettingsBoardsRouteImport } from './routes/_admin/settings/boards'
import { Route as AdminBoardsPostIdRouteImport } from './routes/_admin/boards/$postId'
import { Route as AdminSettingsIntegrationsIndexRouteImport } from './routes/_admin/settings/integrations/index'
import { Route as AdminSettingsIntegrationsGithubRouteImport } from './routes/_admin/settings/integrations/github'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/_auth/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWidgetRoute = AdminWidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorRoute = AdminEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsIndexRoute = AdminRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBoardsIndexRoute = AdminBoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthAcceptInvitationIdRoute = AuthAcceptInvitationIdRouteImport.update({
  id: '/_auth/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsPricingRoute = AdminSettingsPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsMembersRoute = AdminSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsGeneralRoute = AdminSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsFeedbackRoute = AdminSettingsFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsBoardsRoute = AdminSettingsBoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminBoardsPostIdRoute = AdminBoardsPostIdRouteImport.update({
  id: '/boards/$postId',
  path: '/boards/$postId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIntegrationsIndexRoute =
  AdminSettingsIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsIntegrationsGithubRoute =
  AdminSettingsIntegrationsGithubRouteImport.update({
    id: '/integrations/github',
    path: '/integrations/github',
    getParentRoute: () => AdminSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof AdminEditorRoute
  '/settings': typeof AdminSettingsRouteWithChildren
  '/widget': typeof AdminWidgetRoute
  '/auth': typeof AuthAuthRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/boards/$postId': typeof AdminBoardsPostIdRoute
  '/settings/boards': typeof AdminSettingsBoardsRoute
  '/settings/feedback': typeof AdminSettingsFeedbackRoute
  '/settings/general': typeof AdminSettingsGeneralRoute
  '/settings/members': typeof AdminSettingsMembersRoute
  '/settings/pricing': typeof AdminSettingsPricingRoute
  '/accept-invitation/$id': typeof AuthAcceptInvitationIdRoute
  '/boards': typeof AdminBoardsIndexRoute
  '/requests': typeof AdminRequestsIndexRoute
  '/settings/integrations/github': typeof AdminSettingsIntegrationsGithubRoute
  '/settings/integrations': typeof AdminSettingsIntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof AdminEditorRoute
  '/settings': typeof AdminSettingsRouteWithChildren
  '/widget': typeof AdminWidgetRoute
  '/auth': typeof AuthAuthRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/boards/$postId': typeof AdminBoardsPostIdRoute
  '/settings/boards': typeof AdminSettingsBoardsRoute
  '/settings/feedback': typeof AdminSettingsFeedbackRoute
  '/settings/general': typeof AdminSettingsGeneralRoute
  '/settings/members': typeof AdminSettingsMembersRoute
  '/settings/pricing': typeof AdminSettingsPricingRoute
  '/accept-invitation/$id': typeof AuthAcceptInvitationIdRoute
  '/boards': typeof AdminBoardsIndexRoute
  '/requests': typeof AdminRequestsIndexRoute
  '/settings/integrations/github': typeof AdminSettingsIntegrationsGithubRoute
  '/settings/integrations': typeof AdminSettingsIntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/editor': typeof AdminEditorRoute
  '/_admin/settings': typeof AdminSettingsRouteWithChildren
  '/_admin/widget': typeof AdminWidgetRoute
  '/_auth/auth': typeof AuthAuthRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_admin/boards/$postId': typeof AdminBoardsPostIdRoute
  '/_admin/settings/boards': typeof AdminSettingsBoardsRoute
  '/_admin/settings/feedback': typeof AdminSettingsFeedbackRoute
  '/_admin/settings/general': typeof AdminSettingsGeneralRoute
  '/_admin/settings/members': typeof AdminSettingsMembersRoute
  '/_admin/settings/pricing': typeof AdminSettingsPricingRoute
  '/_auth/accept-invitation/$id': typeof AuthAcceptInvitationIdRoute
  '/_admin/boards/': typeof AdminBoardsIndexRoute
  '/_admin/requests/': typeof AdminRequestsIndexRoute
  '/_admin/settings/integrations/github': typeof AdminSettingsIntegrationsGithubRoute
  '/_admin/settings/integrations/': typeof AdminSettingsIntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/settings'
    | '/widget'
    | '/auth'
    | '/onboarding'
    | '/boards/$postId'
    | '/settings/boards'
    | '/settings/feedback'
    | '/settings/general'
    | '/settings/members'
    | '/settings/pricing'
    | '/accept-invitation/$id'
    | '/boards'
    | '/requests'
    | '/settings/integrations/github'
    | '/settings/integrations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor'
    | '/settings'
    | '/widget'
    | '/auth'
    | '/onboarding'
    | '/boards/$postId'
    | '/settings/boards'
    | '/settings/feedback'
    | '/settings/general'
    | '/settings/members'
    | '/settings/pricing'
    | '/accept-invitation/$id'
    | '/boards'
    | '/requests'
    | '/settings/integrations/github'
    | '/settings/integrations'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_admin/editor'
    | '/_admin/settings'
    | '/_admin/widget'
    | '/_auth/auth'
    | '/onboarding/'
    | '/_admin/boards/$postId'
    | '/_admin/settings/boards'
    | '/_admin/settings/feedback'
    | '/_admin/settings/general'
    | '/_admin/settings/members'
    | '/_admin/settings/pricing'
    | '/_auth/accept-invitation/$id'
    | '/_admin/boards/'
    | '/_admin/requests/'
    | '/_admin/settings/integrations/github'
    | '/_admin/settings/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthAuthRoute: typeof AuthAuthRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  AuthAcceptInvitationIdRoute: typeof AuthAcceptInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/widget': {
      id: '/_admin/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof AdminWidgetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/editor': {
      id: '/_admin/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AdminEditorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/requests/': {
      id: '/_admin/requests/'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AdminRequestsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/boards/': {
      id: '/_admin/boards/'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof AdminBoardsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/accept-invitation/$id': {
      id: '/_auth/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AuthAcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/settings/pricing': {
      id: '/_admin/settings/pricing'
      path: '/pricing'
      fullPath: '/settings/pricing'
      preLoaderRoute: typeof AdminSettingsPricingRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/_admin/settings/members': {
      id: '/_admin/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AdminSettingsMembersRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/_admin/settings/general': {
      id: '/_admin/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AdminSettingsGeneralRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/_admin/settings/feedback': {
      id: '/_admin/settings/feedback'
      path: '/feedback'
      fullPath: '/settings/feedback'
      preLoaderRoute: typeof AdminSettingsFeedbackRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/_admin/settings/boards': {
      id: '/_admin/settings/boards'
      path: '/boards'
      fullPath: '/settings/boards'
      preLoaderRoute: typeof AdminSettingsBoardsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/_admin/boards/$postId': {
      id: '/_admin/boards/$postId'
      path: '/boards/$postId'
      fullPath: '/boards/$postId'
      preLoaderRoute: typeof AdminBoardsPostIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/integrations/': {
      id: '/_admin/settings/integrations/'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AdminSettingsIntegrationsIndexRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/_admin/settings/integrations/github': {
      id: '/_admin/settings/integrations/github'
      path: '/integrations/github'
      fullPath: '/settings/integrations/github'
      preLoaderRoute: typeof AdminSettingsIntegrationsGithubRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
  }
}

interface AdminSettingsRouteChildren {
  AdminSettingsBoardsRoute: typeof AdminSettingsBoardsRoute
  AdminSettingsFeedbackRoute: typeof AdminSettingsFeedbackRoute
  AdminSettingsGeneralRoute: typeof AdminSettingsGeneralRoute
  AdminSettingsMembersRoute: typeof AdminSettingsMembersRoute
  AdminSettingsPricingRoute: typeof AdminSettingsPricingRoute
  AdminSettingsIntegrationsGithubRoute: typeof AdminSettingsIntegrationsGithubRoute
  AdminSettingsIntegrationsIndexRoute: typeof AdminSettingsIntegrationsIndexRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsBoardsRoute: AdminSettingsBoardsRoute,
  AdminSettingsFeedbackRoute: AdminSettingsFeedbackRoute,
  AdminSettingsGeneralRoute: AdminSettingsGeneralRoute,
  AdminSettingsMembersRoute: AdminSettingsMembersRoute,
  AdminSettingsPricingRoute: AdminSettingsPricingRoute,
  AdminSettingsIntegrationsGithubRoute: AdminSettingsIntegrationsGithubRoute,
  AdminSettingsIntegrationsIndexRoute: AdminSettingsIntegrationsIndexRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

interface AdminRouteChildren {
  AdminEditorRoute: typeof AdminEditorRoute
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminWidgetRoute: typeof AdminWidgetRoute
  AdminBoardsPostIdRoute: typeof AdminBoardsPostIdRoute
  AdminBoardsIndexRoute: typeof AdminBoardsIndexRoute
  AdminRequestsIndexRoute: typeof AdminRequestsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEditorRoute: AdminEditorRoute,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminWidgetRoute: AdminWidgetRoute,
  AdminBoardsPostIdRoute: AdminBoardsPostIdRoute,
  AdminBoardsIndexRoute: AdminBoardsIndexRoute,
  AdminRequestsIndexRoute: AdminRequestsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthAuthRoute: AuthAuthRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  AuthAcceptInvitationIdRoute: AuthAcceptInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
