name = "admin"
compatibility_date = "2025-02-13"

routes = [
  { pattern = "app.openfeedback.tech/*", zone_name = "openfeedback.tech" },
]

[assets]
directory = "./dist"
not_found_handling = "single-page-application" 

[observability]
enabled = true

