import type React from 'react';

export const styles = {
  form: {
    display: 'flex',
    height: '100%',
    flexDirection: 'column',
  } as React.CSSProperties,
  container: {
    padding: '20px',
  } as React.CSSProperties,
  inputContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  } as React.CSSProperties,
  input: {
    width: '100%',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
    paddingLeft: '12px',
    paddingRight: '12px',
    paddingTop: '12px',
    paddingBottom: '12px',
    fontWeight: 500,
    fontSize: '16px',
    outline: 'none',
  } as React.CSSProperties,
  textareaContainer: {
    marginTop: '12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  } as React.CSSProperties,
  textarea: {
    width: '100%',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
    paddingLeft: '12px',
    paddingRight: '12px',
    paddingTop: '12px',
    paddingBottom: '12px',
    fontSize: '14px',
    outline: 'none',
    resize: 'vertical',
  } as React.CSSProperties,
  charCount: {
    textAlign: 'right',
    color: '#6b7280',
    fontSize: '12px',
  } as React.CSSProperties,
  footer: {
    marginTop: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
  } as React.CSSProperties,
  dropdownButton: (isLoading: boolean, isDisabled: boolean) =>
    ({
      display: 'flex',
      minWidth: '12rem',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: '8px',
      border: '1px solid #e5e7eb',
      backgroundColor: '#f9fafb',
      paddingLeft: '12px',
      paddingRight: '12px',
      paddingTop: '8px',
      paddingBottom: '8px',
      textAlign: 'left',
      fontSize: '14px',
      outline: 'none',
      opacity: isLoading || isDisabled ? 0.6 : 1,
      cursor: 'pointer',
    }) as React.CSSProperties,
  dropdownMenu: {
    position: 'absolute',
    bottom: '100%',
    left: 0,
    zIndex: 1_000_002,
    marginBottom: '4px',
    width: '100%',
    borderRadius: '6px',
    border: '1px solid #e5e7eb',
    backgroundColor: 'white',
    boxShadow:
      '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)',
  } as React.CSSProperties,
  dropdownList: {
    maxHeight: '240px',
    overflow: 'auto',
    paddingTop: '4px',
    paddingBottom: '4px',
  } as React.CSSProperties,
  dropdownItem: (isSelected: boolean) =>
    ({
      display: 'flex',
      width: '100%',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingLeft: '12px',
      paddingRight: '12px',
      paddingTop: '8px',
      paddingBottom: '8px',
      textAlign: 'left',
      fontSize: '14px',
      backgroundColor: isSelected ? '#f9fafb' : 'transparent',
      border: 'none',
      cursor: 'pointer',
    }) as React.CSSProperties,
  submitButton: (isDisabled: boolean) =>
    ({
      borderRadius: '8px',
      backgroundColor: isDisabled ? '#9ca3af' : '#2563eb',
      paddingLeft: '16px',
      paddingRight: '16px',
      paddingTop: '8px',
      paddingBottom: '8px',
      fontWeight: 600,
      fontSize: '14px',
      color: 'white',
      cursor: isDisabled ? 'not-allowed' : 'pointer',
      border: 'none',
    }) as React.CSSProperties,
  error: {
    marginTop: '12px',
    borderRadius: '6px',
    border: '1px solid #fecaca',
    backgroundColor: '#fef2f2',
    paddingLeft: '12px',
    paddingRight: '12px',
    paddingTop: '8px',
    paddingBottom: '8px',
    color: '#b91c1c',
    fontSize: '14px',
  } as React.CSSProperties,
};
