/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicRoadmapRouteImport } from './routes/_public/roadmap'
import { Route as PublicChangelogRouteImport } from './routes/_public/changelog'
import { Route as PublicBoardRouteImport } from './routes/_public/board'
import { Route as PublicBoardIndexRouteImport } from './routes/_public/board/index'
import { Route as PublicBoardPostIdRouteImport } from './routes/_public/board/$postId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoadmapRoute = PublicRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => PublicRoute,
} as any)
const PublicChangelogRoute = PublicChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBoardRoute = PublicBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBoardIndexRoute = PublicBoardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicBoardRoute,
} as any)
const PublicBoardPostIdRoute = PublicBoardPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PublicBoardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/board': typeof PublicBoardRouteWithChildren
  '/changelog': typeof PublicChangelogRoute
  '/roadmap': typeof PublicRoadmapRoute
  '/board/$postId': typeof PublicBoardPostIdRoute
  '/board/': typeof PublicBoardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof PublicChangelogRoute
  '/roadmap': typeof PublicRoadmapRoute
  '/board/$postId': typeof PublicBoardPostIdRoute
  '/board': typeof PublicBoardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteWithChildren
  '/auth': typeof AuthRoute
  '/_public/board': typeof PublicBoardRouteWithChildren
  '/_public/changelog': typeof PublicChangelogRoute
  '/_public/roadmap': typeof PublicRoadmapRoute
  '/_public/board/$postId': typeof PublicBoardPostIdRoute
  '/_public/board/': typeof PublicBoardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/board'
    | '/changelog'
    | '/roadmap'
    | '/board/$postId'
    | '/board/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/changelog' | '/roadmap' | '/board/$postId' | '/board'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/auth'
    | '/_public/board'
    | '/_public/changelog'
    | '/_public/roadmap'
    | '/_public/board/$postId'
    | '/_public/board/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRoute: typeof PublicRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/roadmap': {
      id: '/_public/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof PublicRoadmapRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/changelog': {
      id: '/_public/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof PublicChangelogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/board': {
      id: '/_public/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof PublicBoardRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/board/': {
      id: '/_public/board/'
      path: '/'
      fullPath: '/board/'
      preLoaderRoute: typeof PublicBoardIndexRouteImport
      parentRoute: typeof PublicBoardRoute
    }
    '/_public/board/$postId': {
      id: '/_public/board/$postId'
      path: '/$postId'
      fullPath: '/board/$postId'
      preLoaderRoute: typeof PublicBoardPostIdRouteImport
      parentRoute: typeof PublicBoardRoute
    }
  }
}

interface PublicBoardRouteChildren {
  PublicBoardPostIdRoute: typeof PublicBoardPostIdRoute
  PublicBoardIndexRoute: typeof PublicBoardIndexRoute
}

const PublicBoardRouteChildren: PublicBoardRouteChildren = {
  PublicBoardPostIdRoute: PublicBoardPostIdRoute,
  PublicBoardIndexRoute: PublicBoardIndexRoute,
}

const PublicBoardRouteWithChildren = PublicBoardRoute._addFileChildren(
  PublicBoardRouteChildren,
)

interface PublicRouteChildren {
  PublicBoardRoute: typeof PublicBoardRouteWithChildren
  PublicChangelogRoute: typeof PublicChangelogRoute
  PublicRoadmapRoute: typeof PublicRoadmapRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicBoardRoute: PublicBoardRouteWithChildren,
  PublicChangelogRoute: PublicChangelogRoute,
  PublicRoadmapRoute: PublicRoadmapRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRoute: PublicRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
